[gcp_service_account]
type = "service_account"
project_id = "dglee-499402"
private_key_id = "cae6c342dba7fd3d8311d301eb9768fd1f3aaa12"
private_key = """-----BEGIN PRIVATE KEY-----
MIIEvwIBADANBgkqhkiG9w0BAQEFAASCBKkwggSlAgEAAoIBAQDBhcIzkK1Tg1/y
hzARt10aw9zb9y4kJFfG61sKTPZPcg0CsJEub/7PPE1PMReOhFikX7M51Lx/aEAl
nDuc+lBV7OVSzypv+XRe6oDFcD8okgDo9LO0N2RbGZwae3SEiRkSNGRwKSk2Z+Db
61GuCcEvL8ls0knCmrmI341h8/weUTov/RvlIS9MWgF7XDwA3PcyRnxIrwIATr0C
ijnU505Xf8Sdk9GBsxc99+fvQr6rDj/SZsRoCYHHxQCNX55SWH6WaGx4n+uWVdGY
phmoAa93UJQZxWhgsZxkSq6UO24aAFGZJdo2hRFcudgY1aVQQU0RdhRLlfIXLLu+
75lRDbT3AgMBAAECggEAA3qeRfi1B6TQzevckzJK2Vx/CnH0TDsJBu7xOTYD/DlO
fudiB3CE/KsWsAnvufoAG/MKe6DVmKwXnHV6uYo4dSr9PmgHWRxQxBS5fD3V14AJ
xdEBsAeKOtGy4DkARxJYjIlmQCvv7TtLLA5GxCGxwuGRi0Qb269AuZ4HN8+/5GLv
uOsH8j/8F+iJB3ULxK93toumWCQz0mfX5TBz4DlvwsX1en9ERczLL9GDqSuR8PDv
2/LauNSnv5Hrm1AgituQI4VNNbj+tQANCd15Gqk3sKCbjAYMzzR4zOlYdiVLGvQZ
2NePFA0i8/i7oRGtulzz4QllngYN68FrN/hQbaBVjQKBgQD4EN+N62f1fWSOt8Qc
fgpU+ZumeeEBNiv02yvKD4Ld9sJuKFvLhffYlgd45MXEuuaRP0RKd/to3z1Z3vvF
Ye30/QiRxexaMqcOoIAm4kcQ3Gge+osOn7w8nlP++iq/DEzNed+7pYJDB+/8Bb0n
iBl4jG37ZRHBLC991gtynJ62pQKBgQDHtkq+VUnmgJAPuBkR6qJ0TG8a80x40Slq
iEaOn6ANGsxGmwJ52ugeCeROca94pmmiuKSFhbhJv7c8FmtpVFhbzkv1a0c6w/UC
XOTzNssFV893xfl0UOLUxXYLJ2QahUXUYsMKVbeo+HlCtpLCXOvqQCoIcKxms5Ro
FmfZXRmGawKBgQDheuTZKSq7l5i5qQvXIjHd/2ydq5b79POLg1SQO/0mKM+eNY0K
t+EKu4RbPQcOxRwi1jEKx3h8YL5xXB/Z0CPtVbpeVlt5uSTkRLt3nKIgD1eNIQsY
5dTB/OA4mcgVE+cTtj3JYK3ApAxdNhIzRqBwVKT7p2i1/6XDabXKHdaeCQKBgQDF
xuuCTmhfE1aXmpOJQLodPkyRffxvcYP4cnidactQ7wb5rSzojDdu+BDW9pL1gqf+
c6jKakC1GF1X7kP1DYhrcoOayeDCe6k569D4Y3zvD6TwUmjWHfxlBh/+r8Xc1brv
t9a7d2PovBkqTjBMt0USuPRnY134X0NLSVUS17YdfQKBgQCuQNfawJXHgb/BPkqA
RqSbTtmGONAOG1sWDbw7OsCvcoQ5J9Xb6TBlCgtDPZ1zEF46xXExYXE6E0GzSk6E
b+DqIn5wgAK42alfF4/cxtO/MlQ+k4b4Z5hlXg39KAmPtdcgpPNLUJVyzZNwpfHf
6J0Tzj82db9/wMXrYwZLItb7yQ==
-----END PRIVATE KEY-----
"""
client_email = "dg-quant-db@dglee-499402.iam.gserviceaccount.com"
client_id = "111881727874044538216"
auth_uri = "https://accounts.google.com/o/oauth2/auth"
token_uri = "https://oauth2.googleapis.com/token"
auth_provider_x509_cert_url = "https://www.googleapis.com/oauth2/v1/certs"
client_x509_cert_url = "https://www.googleapis.com/robot/v1/metadata/x509/dg-quant-db%40dglee-499402.iam.gserviceaccount.com"
